# Generated by Django 3.1.1 on 2020-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
                ('time_creation', models.TimeField(auto_now=True)),
                ('link', models.SlugField(unique=True)),
                ('draft', models.BooleanField()),
                ('publish', models.BooleanField()),
            ],
            options={
                'ordering': ['time_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('link', models.SlugField(unique=True)),
                ('posts', models.ManyToManyField(to='blog.Post')),
            ],
        ),
    ]
